# Generated by Django 6.0.3 on 2026-03-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('vote_type', models.CharField(max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='headerapp.reportedurl')),
            ],
            options={
                'unique_together': {('report', 'ip_address')},
            },
        ),
    ]
