# Generated by Django 6.0.3 on 2026-03-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headerapp', '0005_otprecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRecord',
        ),
    ]
